// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// GMDetailPane renders the quest notes and information panel for GM
func GMDetailPane() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"h-48 border border-border/60 rounded-lg bg-surface/80 backdrop-blur-sm overflow-hidden flex flex-col\"><!-- Tab Navigation --><div class=\"flex border-b border-border/60 bg-surface-dark\"><button class=\"gm-detail-tab px-4 py-2 text-sm font-medium transition-colors border-b-2 border-amber-500 text-amber-400\" data-tab=\"quest-notes\">Quest Notes</button> <button class=\"gm-detail-tab px-4 py-2 text-sm font-medium transition-colors border-b-2 border-transparent text-slate-400 hover:text-slate-200\" data-tab=\"monster-stats\">Monster Stats</button> <button class=\"gm-detail-tab px-4 py-2 text-sm font-medium transition-colors border-b-2 border-transparent text-slate-400 hover:text-slate-200\" data-tab=\"quest-rules\">Quest Rules</button></div><!-- Tab Content --><div class=\"flex-1 overflow-y-auto p-4\"><!-- Quest Notes Tab --><div id=\"gm-tab-quest-notes\" class=\"gm-detail-content space-y-3\"><h3 id=\"quest-detail-title\" class=\"text-lg font-bold text-amber-400 mb-2\">Quest Notes</h3><div id=\"quest-detail-content\" class=\"text-sm text-slate-300 space-y-2\"><p>Quest objectives and notes will be loaded...</p></div></div><!-- Monster Stats Tab --><div id=\"gm-tab-monster-stats\" class=\"gm-detail-content hidden\"><h3 class=\"text-lg font-bold text-amber-400 mb-2\">Monster Statistics</h3><div id=\"monster-stats-content\" class=\"space-y-3 text-sm\"><div class=\"text-slate-400\">Select a monster to view detailed stats</div></div></div><!-- Quest Rules Tab --><div id=\"gm-tab-quest-rules\" class=\"gm-detail-content hidden\"><h3 class=\"text-lg font-bold text-amber-400 mb-2\">Quest-Specific Rules</h3><div id=\"quest-rules-content\" class=\"text-sm text-slate-300 space-y-2\"><p>Quest rules will be loaded...</p></div></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
