/**
 * Reads a quest and its board from the database (read-only) and writes its
 * encounters for the combat simulator:
 *   bun scripts/quest-encounters.ts "Crumbling Halls" docs/campaigns/three-plagues/sim/crumbling-halls.json
 * DATABASE_URL comes from .env (Bun loads it). Rerun after moving monsters on the board.
 */

import { SQL } from 'bun';
import { questEncounters } from '../internal/web/src/combat/encounters.ts';
import type { BoardDoc, QuestDoc } from '../internal/web/src/maps/types.ts';

/** Monster types that never fight (NPCs). */
const SKIP = ['stranger'];

const [name, out] = process.argv.slice(2);
if (!name || !out) {
  console.error('usage: bun scripts/quest-encounters.ts "<quest name>" <output.json>');
  process.exit(2);
}
const url = process.env.DATABASE_URL;
if (!url) {
  console.error('DATABASE_URL is not set');
  process.exit(2);
}

const db = new SQL(url);
const rows: { quest: QuestDoc; board: BoardDoc }[] = await db`
  select q.doc as quest, b.doc as board
  from quest q join board b on b.id = q.board_id
  where q.name = ${name}`;
await db.close();
const row = rows[0];
if (!row || rows.length > 1) {
  console.error(`expected one quest named ${JSON.stringify(name)}, found ${rows.length}`);
  process.exit(1);
}

const encounters = questEncounters(row.board, row.quest, SKIP);
const doc = {
  quest: name,
  note: 'Generated by scripts/quest-encounters.ts from the board; nearest first by walking distance (null = unreachable without secret routes).',
  encounters: encounters.map((e) => ({ name: e.name, distance: Number.isFinite(e.distance) ? e.distance : null, monsters: e.monsters })),
};
await Bun.write(out, `${JSON.stringify(doc, null, 2)}\n`);
for (const e of doc.encounters) {
  console.log(`${String(e.distance ?? '-').padStart(3)}  ${e.name}: ${e.monsters.join(', ')}`);
}
